### ISSUE TITLE
Question about LoadPlugins

### ISSUE THREAD

**Issue by woflagship** [rhyous/SimplePluginLoader#1]
In function `PluginLoader.LoadPlugins(string[] pluginFiles)`

```
plugin.Loader.LoadInstances(plugin.Assembly);//1
if (plugin?.PluginObjects?.Count == 0)//2
    continue;
```
1. Invoke `InstancesLoader.Create(Type type)`

2. Also invoke `InstancesLoader.Create(Type type)` since you doesn't update 'PluginObjects' and 'PluginObjects' is still `null`

This means `InstancesLoader.Create(Type type)` is invoked twice and so does the constructor of `Type type`. Is this what you're intended to do? I do think each plugin object should be constructed only once when it is loaded.

**Comment by rhyous** [comment]
Thanks for catching that. I fixed it.
https://github.com/rhyous/SimplePluginLoader/commit/1e950d07794acfca056a7b015c0e1b2d7e941dc9
